spring.application.name=ProfileService

spring.datasource.url=jdbc:mysql://localhost:3306/codesparrow
spring.datasource.username=root
spring.datasource.password=fycs
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=60000

jwt.secret=76d17a27599f51e8076ee2162492b91c7e13a7badd2b75c96c1453aa89987c15

server.port=8085

cloudinary.cloud-name=drwjaxxyy
cloudinary.api-key=875287222527878
cloudinary.api-secret=r4qEeA_hZK-WNdCyQLpA3OVRLvU